<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-4D9NKMKK" failures="3" tests="4" name="PetTest" time="9.474" errors="0" timestamp="2025-07-05T17:18:41 IST">
  <testcase classname="api.tests.UserTests" name="test_postUser" time="2.648"/>
  <testcase classname="api.tests.UserTests" name="test_getUserByUserName" time="1.608">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTests.test_getUserByUserName(UserTests.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test_getUserByUserName -->
  <testcase classname="api.tests.UserTests" name="test_updateUserByName" time="3.06">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTests.test_updateUserByName(UserTests.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test_updateUserByName -->
  <testcase classname="api.tests.UserTests" name="test_deleteUserByUserName" time="1.532">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.UserTests.test_deleteUserByUserName(UserTests.java:84)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test_deleteUserByUserName -->
</testsuite> <!-- PetTest -->
